# Generated by Django 5.2.8 on 2025-11-30 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_home_city', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.FloatField(default=0.0)),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.product')),
                ('id_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.store')),
            ],
        ),
        migrations.CreateModel(
            name='Debiting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.CharField()),
                ('debiting_date', models.DateTimeField(max_length=30)),
                ('id_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.delivery')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.product')),
                ('id_store', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='manager.store')),
            ],
        ),
    ]
