# Generated by Django 5.2.8 on 2025-11-21 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debiting',
            name='debiting_date',
            field=models.DateTimeField(max_length=30),
        ),
    ]
