# Generated by Django 5.2.8 on 2025-11-18 20:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_alter_login_identity_alter_login_last_login_and_more'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_quotation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_operator', models.CharField(max_length=60)),
                ('payment_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Cmd_Contain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.FloatField()),
                ('id_product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.product')),
                ('id_command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.command')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Cmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateField(max_length=10)),
                ('id_command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.command', unique=True)),
                ('id_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user')),
                ('id_payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.payment', unique=True)),
            ],
        ),
    ]
