# Generated by Django 5.2.8 on 2025-11-30 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_quotation', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_operator', models.CharField(max_length=60)),
                ('payment_amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Statement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement_tax', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('client', 'Customer'), ('membre', "Membre d'une cooperative")], default='client', max_length=10)),
                ('user_lastname', models.CharField(max_length=30)),
                ('user_firstname', models.CharField(max_length=60)),
                ('user_email', models.EmailField(max_length=100, unique=True)),
                ('user_contact', models.CharField(max_length=26, unique=True)),
                ('user_home_city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cmd_Contain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.FloatField()),
                ('id_command', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.command')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Cmd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_payment', models.DateTimeField(max_length=10)),
                ('id_command', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.command')),
                ('id_payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.payment')),
                ('id_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.user')),
            ],
        ),
    ]
