# Generated by Django 5.2.8 on 2025-11-30 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmd_contain',
            name='id_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.product'),
        ),
    ]
