# Generated by Django 5.2.8 on 2025-11-21 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_statement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cmd',
            name='date_payment',
            field=models.DateTimeField(max_length=10),
        ),
    ]
