# Generated by Django 5.2.8 on 2025-11-22 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_user_home_city'),
        ('customer', '0003_alter_order_cmd_date_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_cmd',
            name='id_command',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.command'),
        ),
        migrations.AlterField(
            model_name='order_cmd',
            name='id_payment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.payment'),
        ),
        migrations.AlterField(
            model_name='order_cmd',
            name='id_user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user'),
        ),
    ]
