# Generated by Django 5.2.8 on 2025-11-30 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_person', models.CharField(max_length=90)),
                ('delivery_sender', models.CharField(max_length=90)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Function',
            fields=[
                ('type_function', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Module_Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_formation_name', models.CharField(max_length=100)),
                ('m_formation_desc', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=60)),
                ('product_unity_price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Having_Function',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
                ('type_function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member_function')),
            ],
        ),
        migrations.CreateModel(
            name='Inject_Prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.FloatField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.user')),
                ('id_product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.product')),
            ],
        ),
        migrations.CreateModel(
            name='Render_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('render_up_date', models.DateTimeField(max_length=30)),
                ('id_command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.command')),
                ('id_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.delivery')),
                ('id_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.statement')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.user')),
            ],
        ),
        migrations.CreateModel(
            name='Waching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waching_date', models.DateTimeField()),
                ('waching_nb', models.IntegerField(default=0)),
                ('id_m_formation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.module_formation')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.user')),
            ],
        ),
    ]
