# Generated by Django 5.2.8 on 2025-11-21 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_delivery_member_function_module_formation_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Render_up',
        ),
    ]
