# Generated by Django 5.2.8 on 2025-11-22 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_user_user_home_city'),
        ('customer', '0003_alter_order_cmd_date_payment'),
        ('member', '0003_delete_render_up'),
    ]

    operations = [
        migrations.CreateModel(
            name='Render_up',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('render_up_date', models.DateTimeField(max_length=30)),
                ('id_command', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customer.command')),
                ('id_delivery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='member.delivery')),
                ('id_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.statement')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.user')),
            ],
        ),
    ]
