# Generated by Django 5.2.8 on 2025-11-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='identity',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='login',
            name='last_login',
            field=models.DateTimeField(max_length=30),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_home_city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
