# Generated by Django 5.2.8 on 2025-11-21 20:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_login_identity_alter_login_last_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_home_city',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
